# Generated by Django 4.0.3 on 2022-03-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blood_grup',
            new_name='blood_group',
        ),
    ]
